"""added about_me field to User

Revision ID: 144e0c053ef1
Revises: 833caf358842
Create Date: 2019-03-29 11:40:57.442761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '144e0c053ef1'
down_revision = '833caf358842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
